//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestHackWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityService
    {
        public string ServiceApprovalNumber { get; set; }
        public string Provider_Approval_Number { get; set; }
        public string ServiceName { get; set; }
        public string ProviderLegalName { get; set; }
        public string ServiceAddress { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email_Address { get; set; }
        public string Conditions_on_Approval { get; set; }
        public Nullable<int> NumberOfApprovedPlaces { get; set; }
        public Nullable<System.DateTime> ServiceApprovalGrantedDate { get; set; }
        public string QualityArea1Rating { get; set; }
        public string QualityArea2Rating { get; set; }
        public string QualityArea3Rating { get; set; }
        public string QualityArea4Rating { get; set; }
        public string QualityArea5Rating { get; set; }
        public string QualityArea6Rating { get; set; }
        public string QualityArea7Rating { get; set; }
        public string OverallRating { get; set; }
    }
}
